# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# The following list can be more neatly rewritten as:
['Afghan',
'African',
'Afternoon Tea',
'American',
'Argentinean',
'Asian',
'Australian',
'Bar/Lounge/Bottle Service',
'Barbecue',
'Beer Garden',
'Bistro',
'Brazilian',
'Brazilian Steakhouse',
'Breakfast',
'Brewery',
'British',
'Burgers',
'Café',
'Cajun',
'Californian',
'Canadian',
'Caribbean',
'Chinese',
'Comfort Food',
'Contemporary American',
'Contemporary Asian',
'Contemporary Canadian',
'Contemporary European',
'Contemporary French',
'Contemporary Indian',
'Contemporary Italian',
'Contemporary Mexican',
'Continental',
'Creperie',
'Dessert',
'Dining Bar',
'Eastern European',
'English',
'Eritrean',
'Ethiopian',
'European',
'Filipino',
'Fine cuts',
'French',
'French / Canadian',
'Fusion / Eclectic',
'Gastro Pub',
'German',
'Global, International',
'Greek',
'Halal',
'Hungarian',
'Indian',
'International',
'Irish',
'Israeli',
'Italian',
'Jamaican',
'Japanese',
'Japanese Specialty',
'Korean',
'Latin / Spanish',
'Latin American',
'Mediterranean',
'Mexican',
'Mexican / Southwestern',
'Middle Eastern',
'Modern European',
'Moroccan',
'Northwest',
'Organic',
'Pakistani',
'Pan-Asian',
'Pizzeria',
'Polish',
'Portuguse',
'Prime Rib',
'Provencal',
'Seafood',
'Sicilian',
'Soul food',
'South American',
'Southern',
'Southwest',
'Spanish',
'Steak',
'Steakhouse',
'Sushi',
'Tapas / Small Plates',
'Tex-Mex',
'Thai',
'Traditional Mexican',
'Vegan',
'Vegetarian / Vegan',
'Wine Bar'].each { |name| Category.create name: name }
